name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create the config.json file using GitHub secrets
      - name: Set up Firebase Config
        run: |
          echo '{
            "apiKey": "${{ secrets.FIREBASE_API_KEY }}",
            "authDomain": "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            "projectId": "${{ secrets.FIREBASE_PROJECT_ID }}",
            "storageBucket": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            "messagingSenderId": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            "appId": "${{ secrets.FIREBASE_APP_ID }}"
          }' > ./config.json

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
